---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver:
      box: chef/ubuntu-12.04
      box_url: chef/ubuntu-12.04
  - name: ubuntu-14.04
    driver:
      box: chef/ubuntu-14.04
      box_url: chef/ubuntu-14.04
  - name: debian-7.4
    driver:
      box: chef/debian-7.4
      box_url: chef/debian-7.4

suites:
  - name: default
    run_list:
      - recipe[tinc::default]
    attributes:
